Document: glslviewer
Title: Debian glslviewer Manual
Author: <insert document author here>
Abstract: This manual describes what glslviewer is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glslviewer/glslviewer.sgml.gz

Format: postscript
Files: /usr/share/doc/glslviewer/glslviewer.ps.gz

Format: text
Files: /usr/share/doc/glslviewer/glslviewer.text.gz

Format: HTML
Index: /usr/share/doc/glslviewer/html/index.html
Files: /usr/share/doc/glslviewer/html/*.html
